import { Roboto } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import ConvexClientProvider from "./ConvexClientProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: "500",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${roboto.className} bg-slate-900 text-neutral-50`}>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
